<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversalNewsFeedApp.Models\UniversalNewsFeedApp.Models.csproj" />
    <ProjectReference Include="..\UniversalNewsFeedApp.Services\UniversalNewsFeedApp.Services.csproj" />
  </ItemGroup>

</Project>
