<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config\sources.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config\sources.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversalNewsFeedApp.ViewModels\UniversalNewsFeedApp.ViewModels.csproj" />
  </ItemGroup>

</Project>
